import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "./components/QueryProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Header } from "./(routes)/(home)/components/Header";
import { Suspense } from "react";
import { HeaderFallback } from "./(routes)/(home)/components/Header/HeaderFallback";
import { OnBeforeUnload } from "./components/OnBeforeUnload";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Cacau Store",
    default: "Cacau Store",
  },
  description: "Generated by create next app",
};

export const revalidate = 1;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Suspense fallback={<HeaderFallback />}>
          <Header />
        </Suspense>
        <QueryProvider>{children}</QueryProvider>
        <ToastContainer />
        <OnBeforeUnload />
      </body>
    </html>
  );
}
